# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode Version
      run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Cache Swift Packages
      uses: actions/cache@v1
      with:
       path: SourcePackages
       key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
       restore-keys: ${{ runner.os }}-spm-
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build
