ENV['ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD'] = 'true'
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "900"

default_platform(:ios)

platform :ios do

	before_all do
  if is_ci?
		setup_ci
  end
end

  desc "Test"
  lane :test do
    run_tests(device: "iPhone 14 Pro", 
              scheme: "RealitySuperApp",
							testplan: "RealityTest",
							clean: true,
 cloned_source_packages_path: "SourcePackages")
  end

  lane :release do

	username = ENV['USER_NAME']
  	personal_github_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
  	authorization_token_str = "#{username}:#{personal_github_access_token}"
  	basic_authorization_token = Base64.strict_encode64(authorization_token_str)

	api_key = app_store_connect_api_key(
  	key_id: ENV['ASC_API_KEY_ID'],
  	issuer_id: ENV['ASC_API_ISSUER_ID'],
  	key_content: ENV['ASC_KEY_CONTENT']
	)

	match(
  	git_basic_authorization: basic_authorization_token,
  	api_key: api_key,
  	type: "appstore",
  	readonly: true
	)

    	increment_version_number(xcodeproj: "RealitySuperApp.xcodeproj")
    	increment_build_number

			update_code_signing_settings(
  			path: "RealitySuperApp.xcodeproj",
 			 	code_sign_identity: "iPhone Distribution",
  			profile_name: ENV['PROVISION'],
  			use_automatic_signing: false,
		)

    	build_app(
		scheme: "RealitySuperApp",
		export_options: {
      method: "app-store",
			provisioningProfiles: {
          ENV['APP_ID'] => ENV['PROVISION']
        }
    }
	)

	update_code_signing_settings(
      path: "RealitySuperApp.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      profile_name: ENV['PROVISION'],
      use_automatic_signing: true,
   )

    	upload_to_app_store(
      	api_key: api_key,
      	skip_screenshots: true,
      	skip_metadata: true,
				precheck_include_in_app_purchases: false
   	)
  end

  lane :beta do

	username = ENV['USER_NAME']
  	personal_github_access_token = ENV["PERSONAL_GITHUB_ACCESS_TOKEN"]
  	authorization_token_str = "#{username}:#{personal_github_access_token}"
  	basic_authorization_token = Base64.strict_encode64(authorization_token_str)

	api_key = app_store_connect_api_key(
  	key_id: ENV['ASC_API_KEY_ID'],
  	issuer_id: ENV['ASC_API_ISSUER_ID'],
  	key_content: ENV['ASC_KEY_CONTENT']
	)

	match(
  	git_basic_authorization: basic_authorization_token,
  	api_key: api_key,
  	type: "appstore",
  	readonly: is_ci
	)

increment_version_number(xcodeproj: "RealitySuperApp.xcodeproj")
increment_build_number
update_code_signing_settings(
  path: "RealitySuperApp.xcodeproj",
  code_sign_identity: "iPhone Distribution",
  profile_name: ENV['PROVISION'],
  use_automatic_signing: false,
)

	build_app(
		scheme: "RealitySuperApp",
		export_options: {
      method: "app-store",
			provisioningProfiles: {
          ENV['APP_ID'] => ENV['PROVISION']
        }
    }
	)

	update_code_signing_settings(
      path: "RealitySuperApp.xcodeproj",
      code_sign_identity: "iPhone Distribution",
      profile_name: ENV['PROVISION'],
      use_automatic_signing: true,
   )

	upload_to_testflight(api_key: api_key)
  end
end
