
default_platform(:ios)

platform :ios do
  desc "Test"
  lane :test do
    run_tests(device: "iPhone 14 Pro", 
              scheme: "RealitySuperApp", 
              slack_url: "https://hooks.slack.com/services/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")
  end
  lane :release do
    sync_code_signing(type: "appstore") 
    build_app(scheme: "RealitySuperApp")
    upload_to_app_store(
      username: "kato.1120.3211.haya@icloud.com",
      skip_screenshots: true,
      skip_metadata: true,
      force: true,
    )
   slack(
      message: "Successfully uploaded a new App Store build",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
end
