name: Upload TestFlight

on: workflow_dispatch

jobs: 
  build: 
    runs-on: macos-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: Select Xcode Version
       run: sudo xcode-select -s "/Applications/Xcode_13.2.1.app"
 
     - name: Show Xcode version
       run: xcodebuild -version

     - name: Bundle Install
       run: bundle install
 
     - name: Cache Swift Packages
       uses: actions/cache@v1
       with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-
    
     - name: Upload a TestFlight
       env:
        ASC_KEY_ID: ${{ secrets.ASC_API_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_API_ISSUER_ID }}
        ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        PERSONAL_GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
        USER_NAME: ${{ secrets.USER_NAME }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_ID: ${{ secrets.APP_ID }} 
       run: bundle exec fastlane beta
        
       
       
